# Generated by Django 5.0.1 on 2024-02-03 22:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_question_level_question_subject_question_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('A', 'A level'), ('G', 'GCSE'), ('K', 'KS3')], max_length=5)),
                ('subject', models.CharField(choices=[('CS', 'Computer Science'), ('M', 'Maths'), ('P', 'Physics'), ('C', 'Chemistry'), ('B', 'Biology')], max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='question',
            name='level',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
        migrations.AddField(
            model_name='question',
            name='subjectLevel',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='questions.subjectlevel'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='subjects',
            field=models.ManyToManyField(to='questions.subjectlevel'),
        ),
    ]
