# Generated by Django 5.0.1 on 2024-02-04 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subjectLevel',
            field=models.ForeignKey(choices=[('CS', 'Computer Science'), ('M', 'Maths'), ('P', 'Physics'), ('C', 'Chemistry'), ('B', 'Biology')], on_delete=django.db.models.deletion.CASCADE, to='users.subjectlevel'),
        ),
    ]
